apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-flannel-cfg
  namespace: kube-system
data:
  cni-conf.json: |
    {
        "name": "cbr0",
        "type": "flannel",
        "delegate": {
            "isDefaultGateway": true,
            "ipMasq": true,
            "mtu": 1450,
            "hairpinMode": true
        }
    }
  kube-subnet-mgr.conf: |
    FLANNEL_NETWORK=10.244.0.0/16
    FLANNEL_SUBNET=10.244.1.0/24
    FLANNEL_MTU=1450
    FLANNEL_IPMASQ=true

